### ISSUE TITLE
Unable to get price in lp configured by izumi finance

### ISSUE THREAD

**Issue by Xiaxuliang** [de-dot-fi/defiyield-self-integrations#60]
## Bug Report

**Current Behavior**
price wrong. 

**Expected behavior* *
can get price  by   izumi.finance or dexscreener

**Details**

- Chain: zksync_era
- Address: (0x...) 0x8FdF5A1880832e9043Ce35B729A1e6C850b09b23

**Additional context/Screenshots**
![image](https://github.com/de-dot-fi/defiyield-self-integrations/assets/102294235/27054d36-19c6-438f-b486-16c6bea764ea)

**Comment by Xiaxuliang** [comment]
exmaple： 
dex:
https://api.dexscreener.com/latest/dex/pairs/zksync/0x2f801cc2b7213be05fd73febb80b627cfd625c9f

 izumi.finance:
   /// @notice Estimate amount of tokenX required when an user wants to buy tokenY given amount of tokenX user wants to buy
    ///    calling this function will not generate any real exchanges in the pool.
    /// @param tokenX tokenX of swap pool
    /// @param tokenY tokenY of swap pool
    /// @param fee fee amount of swap pool
    /// @param desireY amount of tokenY user wants to buy
    /// @param lowPt highest point during exchange
    /// @return amountX estimated amount of tokenX user need to pay
    /// @return finalPoint estimated point of pool after swap
    function swapX2YDesireY(
        address tokenX,
        address tokenY,
        uint24 fee,
        uint128 desireY,
        int24 lowPt
    ) public returns (uint256 amountX, int24 finalPoint);

**Comment by witem** [comment]
@Xiaxuliang, you can add `fetchMissingTokenPrices` to the project with some logic. Example: https://github.com/de-dot-fi/defiyield-self-integrations/blob/478bc5eb293a072ac31849d89143a2911c78c040/apps/workshop/projects/CroSwap/modules/CroSwap.ts#L102C9-L124

Or you can just wait when price for this token will be available on coingecko

**Comment by Xiaxuliang** [comment]
has  resolved ，thanks
