### ISSUE TITLE
Pool Bug Report

### ISSUE THREAD

**Issue by xuantuan150495** [de-dot-fi/defiyield-self-integrations#71]
## Bug Report

**Current Behavior**
A description of whats wrong. (Wrong Logo, Wrong APR or TVL, missing pools etc)

**Expected behavior**
(Ideally 😉) A description of how to fix (where to get price from, how to do the correct calculation, etc)

**Details**

- Chain: (ethereum, polygon, etc)
- Project Website:

**Additional context/Screenshots**
Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by witem** [comment]
Please add a correct description of the request.
